Add sandbox mode
robuust/craft-mailjet pull request #3
Opened 2023-09-21 13:36 UTC by wietsedecnijf

2023-09-21 17:14 UTC, boboldehampsink requested changes

2023-09-21 17:14 UTC, boboldehampsink commented on src/MailjetAdapter.php
> +    }
Do you think this is necessary?

2023-09-21 17:14 UTC, boboldehampsink commented on src/templates/settings.html
>  }) }}
Can you fix the indenting of this file?

2023-09-21 17:14 UTC, boboldehampsink commented
Thanks @wietsedecnijf!

2023-09-21 19:08 UTC, wietsedecnijf commented on src/templates/settings.html
>  }) }}
Done

2023-09-21 19:17 UTC, wietsedecnijf commented on src/MailjetAdapter.php
> +    }
I'm not sure, I took Brandon's implementation of the `useAuthentication` setting in the Smtp Adapter as an example: https://github.com/craftcms/cms/blob/72122c099e702529756d2f0a3bc5a582d632cd90/src/mail/transportadapters/Smtp.php#L71
I can remove it is you want.

2023-09-22 05:59 UTC, boboldehampsink commented on src/MailjetAdapter.php
> +    }
Must be good then ;-)

2023-09-22 05:59 UTC, boboldehampsink approved these changes

2023-09-22 05:59 UTC, merged